

summary: |
   Отображение страницы на разных устройствах
  requirement: |
   Корректное отобрадение всех баннеров, товаров при изменении разрешения
  prerequisites: |
   открыты главная страница сайта и панель  разработчика браузера
  test-data: |
  -
  steps:
   изменяем разрешение экрана на:
- 414х896
- 360х740
- 853х1280
- 1280х800
  expected-result: |
    Все баннеры должны равномерно распределятся по экрану, ничего не должно уходить за поле видимости в бок

summary: |
    проверка невозможности заказа товара количеством большим, чем имеется
  requirement: |
 при вводе количества товара, большим чем имеется, должен появится предупреждающий юбаннер
  prerequisites: |
  открыта страница заказа
  test-data: |
 имеется информация о наличие товара
  steps:
    - добавить в корзину товар,количеством превышающим наличие
  expected-result: |
    появился предупреждающий баннер


summary: |
    Краткое описание тест-кейса. Например, проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например, при верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест-кейса. Они должны быть выполнены еще до запуска тест-кейса.
    Например, открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку «Войти»
  expected-result: |
    Пользователь должен попасть на главную страницу


summary: |
    Краткое описание тест-кейса. Например, проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например, при верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест-кейса. Они должны быть выполнены еще до запуска тест-кейса.
    Например, открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку «Войти»
  expected-result: |
    Пользователь должен попасть на главную страницу


summary: |
    Краткое описание тест-кейса. Например, проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например, при верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест-кейса. Они должны быть выполнены еще до запуска тест-кейса.
    Например, открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку «Войти»
  expected-result: |
    Пользователь должен попасть на главную страницу

