    summary: |
   Невозможность установить отрицательное значение цены в фильтре
  requirement: |
  Невозможность установить отрицательное значение цены в фильтре  
  prerequisites: 
   открыты главная страница сайта 
  test-data: |
  - цена -"3"
  steps:
- выбор на вкладке "Цена" отрицательного значения цены
  expected-result: |
    при возможности выбора цены 
    status:fail
