summary: |
   Отображение страницы на разных устройствах
  requirement: |
   Корректное отобрадение всех баннеров, товаров при изменении разрешения
  prerequisites: |
   открыты главная страница сайта и панель  разработчика браузера
  test-data: |
  -
  steps:
   изменяем разрешение экрана на:
- 414х896
- 360х740
- 853х1280
- 1280х800
  expected-result: |
    Все баннеры должны равномерно распределятся по экрану, ничего не должно уходить за поле видимости в бок
    status:fail

summary: |
    проверка невозможности заказа товара количеством большим, чем имеется
  requirement: |
 не должно добавляться в корзину товаров количеством большим, чем есть на складе
  prerequisites: |
  открыта страница заказа
  test-data: |
 имеется информация о наличие товара
  steps:
    - добавить в корзину товар,количеством превышающим наличие
  expected-result: |
   максимальное количество товара d rjhpbyt равно количеству на складе
    status:pass

    
summary: |
    невозможность добавления в корзину отсутствующего товара
  requirement: |
 не должно добавляться в корзину товаров товар, отсутствующий на складе
  prerequisites: |
  открыта страница заказа
  test-data: |
 имеется информация о наличие товара
  steps:
    - добавить в корзину товар отсутствующий на складе
    - перейти в корзину, нажать "Checkout"
  expected-result: |
  товар не добавляется в корзину
    status:fail

summary: |
   Перевод страницы и всего содержания на русский язык
  requirement: |
   перевод всех элементов страницы на русский язык
  prerequisites: |
   открыты главная страница сайта 
  test-data: |
  -
  steps:
- выбор на вкладке "Язык" русской версии страницы
  expected-result: |
    Все баннеры должны переводятся на русский язык
    status:fail

    summary: |
   Невозможность установить отрицательное значение цены в фильтре
  requirement: |
  Невозможность установить отрицательное значение цены в фильтре  
  prerequisites: 
   открыты главная страница сайта 
  test-data: |
  - цена -"3"
  steps:
- выбор на вкладке "Цена" отрицательного значения цены
  expected-result: |
    при возможности выбора цены 
    status:fail
