
summary: |
    проверка невозможности заказа товара количеством большим, чем имеется
  requirement: |
 не должно добавляться в корзину товаров количеством большим, чем есть на складе
  prerequisites: |
  открыта страница заказа
  test-data: |
 имеется информация о наличие товара
  steps:
    - добавить в корзину товар,количеством превышающим наличие
  expected-result: |
   максимальное количество товара d rjhpbyt равно количеству на складе
    status:pass
