summary: |
   Отображение страницы на разных устройствах
  requirement: |
   Корректное отобрадение всех баннеров, товаров при изменении разрешения
  prerequisites: |
   открыты главная страница сайта и панель  разработчика браузера
  test-data:
  steps:
   изменяем разрешение экрана на:
- 414х896
- 360х740
- 853х1280
- 1280х800
  expected-result: |
    Все баннеры должны равномерно распределятся по экрану, ничего не должно уходить за поле видимости в бок
    status:fail
